# Generated by Django 2.0 on 2020-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048, verbose_name='文献标题')),
                ('publish_year', models.IntegerField(default=2019, verbose_name='发布年份')),
                ('authors', models.TextField(verbose_name='作者列表')),
                ('abstract', models.TextField(verbose_name='文献摘要')),
                ('doi_url', models.TextField(verbose_name='原文详情页链接')),
                ('references', models.TextField(verbose_name='引用列表')),
                ('publication', models.TextField(verbose_name='文献发表信息')),
                ('classification', models.IntegerField(blank=True, default=-1, null=True, verbose_name='所属类别')),
            ],
            options={
                'verbose_name_plural': '文献',
                'verbose_name': '文献',
            },
        ),
    ]
