# Generated by Django 2.0 on 2020-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrievalCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_vector', models.TextField(verbose_name='D向量')),
                ('P_vector', models.TextField(verbose_name='P向量')),
                ('precision', models.FloatField(verbose_name='此此session的准确率')),
            ],
            options={
                'verbose_name_plural': '会话',
                'verbose_name': '会话',
            },
        ),
    ]
