# Generated by Django 2.0 on 2020-04-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrievalCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='D_vector',
            field=models.TextField(blank=True, null=True, verbose_name='D向量'),
        ),
        migrations.AlterField(
            model_name='session',
            name='P_vector',
            field=models.TextField(blank=True, null=True, verbose_name='P向量'),
        ),
        migrations.AlterField(
            model_name='session',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='此此session的准确率'),
        ),
    ]
