# Generated by Django 2.0 on 2020-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrievalCore', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='feature_vector',
            field=models.TextField(blank=True, null=True, verbose_name='特征向量'),
        ),
    ]
