# Generated by Django 2.0 on 2020-04-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetrievalCore', '0003_auto_20200410_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVectorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_D_vector', models.TextField(blank=True, null=True, verbose_name='用户D向量')),
                ('sys_D_vector', models.TextField(blank=True, null=True, verbose_name='系统计算的D向量')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': 'D向量比对表',
                'verbose_name': 'D向量比对表',
            },
        ),
    ]
